#!/usr/bin/env bash
# ^ added for shellcheck and file-type detection

layout_python_uv() {
    local python=${1:-python}
    [[ $# -gt 0 ]] && shift
    unset PYTHONHOME
    local python_path
    python_path=$(uv python find "$python")
    local python_version
    python_version=$($python_path -V | cut -d' ' -f 2 | cut -d . -f 1-2)
    if [[ -z $python_version ]]; then
        log_error "Could not find python's version"
        return 1
    fi

    if [[ -n ${VIRTUAL_ENV:-} ]]; then
        local REPLY
        realpath.absolute "$VIRTUAL_ENV"
        VIRTUAL_ENV=$REPLY
    else
        # use uv's default venv dir
        VIRTUAL_ENV=.venv
    fi
    export UV_PROJECT_ENVIRONMENT=$VIRTUAL_ENV
    if [[ ! -d $VIRTUAL_ENV ]]; then
        uv venv -p "$python" "$@" "$VIRTUAL_ENV"
    fi
    export VIRTUAL_ENV
    PATH_add "$VIRTUAL_ENV/bin"
}

# Install git hooks if pre-commit config exists and hooks don't exist
if [ -f .pre-commit-config.yaml ] && { [ ! -f .git/hooks/pre-commit ] || [ ! -f .git/hooks/post-checkout ] || [ ! -f .git/hooks/pre-push ]; }; then
    echo "Installing git hooks..."
    uvx pre-commit install --hook-type pre-commit --hook-type post-checkout --hook-type pre-push
fi

# Load uv virtualenv
layout python_uv python3.13

