[project]
name = "ennos-dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
  { name = "Enno Richter", email = "enno@nerdworks.de" },
]
requires-python = ">=3.12"
dependencies = [
  "rich",
  "rich-click",
  "click",
  "questionary",
  "PyYAML",
  "requests",
  "flask",
  "waitress",
]

[project.scripts]
glab-ghq-cloneall = "scripts.glab_ghq_cloneall:main"
backup-pg = "scripts.backup_pg:cli"
ocauth = "scripts.ocauth:main"
httpserve = "scripts.httpserve:main"
chrome-profile-manager = "scripts.chrome_profile_manager:main"
compress-dir = "scripts.compress_dir:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "scripts"
module-root = ""
