# Split panes using Vim-like bindings
bind-key s split-window -h
bind-key v split-window -v

# Vim-like pane navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# More ergonomic Alt+hjkl pane navigation
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Vim-like window navigation (like tabs)
bind-key -n C-h previous-window
bind-key -n C-l next-window

# Vim-like pane resizing
bind-key -n M-Left resize-pane -L 5
bind-key -n M-Down resize-pane -D 5
bind-key -n M-Up resize-pane -U 5
bind-key -n M-Right resize-pane -R 5

# Vim-like copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
