"""pi-egress addon for mitmproxy: egress filtering and secret injection.

Runs inside the pi-less-yolo-proxy sidecar on an internal Docker network as
the only route out of the pi container.

Responsibilities:
  * allow/deny/interactive filtering at the HTTP CONNECT level (hostname
    based — interception is not needed for filtering)
  * selective TLS interception: only hosts matching an intercept= pattern or
    an active secret rule are MITMed; everything else is tunneled untouched,
    so model-endpoint traffic is never visible to the proxy by default
  * secret injection: the pi container only ever holds random placeholders;
    this addon swaps in the real value for approved host/method combinations
    and blocks any request that carries a placeholder anywhere else
  * redaction: real secret values are stripped from responses before they
    reach the client, and swapped back to placeholders in recorded flows
  * optional flow recording (record=1) for `mise run pi:egress web`

State directory (/egress, host-mounted from ~/.pi/agent/egress):
  config        regenerated by _egress on every run: mode=allowlist|interactive,
                timeout=<s>, allow-private=1, allow=, intercept=, record=1
  rules.allow   persistent user allow patterns, one per line
  rules.deny    persistent user deny patterns, one per line (deny wins)
  secrets.rules persistent secret scopes: NAME hosts=<p,p> [methods=GET,POST]
  secrets.env   regenerated per run, mode 600: NAME<TAB>placeholder<TAB>value
  pending/<id>  written by this addon: "host:port" awaiting a decision
  decisions/<id> written by `pi:egress watch`: allow | allow-session |
                deny | deny-session
  egress.log    append-only decision log
  flows.mitm    recorded flows (only when record=1), placeholders only

Pattern syntax: "host" (ports 80/443), "host:port", "*.suffix" (subdomains
only, not the apex). Matching is case-insensitive. Wildcards never match IP
literals. Deny rules win over allow rules.
"""

import asyncio
import base64
import binascii
import datetime
import ipaddress
import logging
import os
import secrets as pysecrets
import time

from mitmproxy import http, io, tls

logger = logging.getLogger(__name__)

STATE_DIR = os.environ.get("PI_EGRESS_STATE_DIR", "/egress")
PENDING_DIR = os.path.join(STATE_DIR, "pending")
DECISIONS_DIR = os.path.join(STATE_DIR, "decisions")
LOG_FILE = os.path.join(STATE_DIR, "egress.log")
FLOWS_FILE = os.path.join(STATE_DIR, "flows.mitm")
POLL_S = 0.25
GC_MAX_AGE_S = 10 * 60


def _read_lines(path):
    try:
        with open(path, encoding="utf-8") as f:
            return [ln.strip() for ln in f if ln.strip() and not ln.strip().startswith("#")]
    except OSError:
        return []


def _stat_key(path):
    try:
        st = os.stat(path)
        return f"{st.st_mtime_ns}:{st.st_size}"
    except OSError:
        return "absent"


# --- policy -----------------------------------------------------------------

class Secret:
    def __init__(self, name, hosts, methods, placeholder, value):
        self.name = name
        self.hosts = hosts          # list of patterns
        self.methods = methods      # uppercased method names, or ["*"]
        self.placeholder = placeholder.encode()
        self.value = value.encode()

    def method_allowed(self, method):
        return "*" in self.methods or method.upper() in self.methods


class Policy:
    def __init__(self):
        self.mode = "allowlist"
        self.timeout_s = 60
        self.allow_private = False
        self.record = False
        self.intercept_all = False
        self.allow = []
        self.deny = []
        self.intercept = []
        self.secrets = []           # active secrets (rule + value present)


_POLICY_FILES = ["config", "rules.allow", "rules.deny", "secrets.rules", "secrets.env"]
_policy_cache = {"key": None, "policy": Policy()}


def load_policy():
    paths = [os.path.join(STATE_DIR, name) for name in _POLICY_FILES]
    key = "|".join(_stat_key(p) for p in paths)
    if _policy_cache["key"] == key:
        return _policy_cache["policy"]

    policy = Policy()
    for line in _read_lines(paths[0]):
        k, sep, v = line.partition("=")
        if not sep:
            continue
        k, v = k.strip(), v.strip()
        if k == "mode":
            policy.mode = v
        elif k == "timeout":
            try:
                policy.timeout_s = max(1, int(v))
            except ValueError:
                pass
        elif k == "allow-private":
            policy.allow_private = v in ("1", "true")
        elif k == "record":
            policy.record = v in ("1", "true")
        elif k == "allow":
            policy.allow.append(v.lower())
        elif k == "intercept":
            if v.lower() == "all":
                policy.intercept_all = True
            else:
                policy.intercept.append(v.lower())
    policy.allow.extend(ln.lower() for ln in _read_lines(paths[1]))
    policy.deny.extend(ln.lower() for ln in _read_lines(paths[2]))

    # secrets.rules: NAME hosts=<pat,pat> [methods=GET,POST]
    scopes = {}
    for line in _read_lines(paths[3]):
        parts = line.split()
        name, hosts, methods = parts[0], [], ["*"]
        for part in parts[1:]:
            k, sep, v = part.partition("=")
            if k == "hosts" and sep:
                hosts = [h.lower() for h in v.split(",") if h]
            elif k == "methods" and sep:
                methods = [m.upper() for m in v.split(",") if m]
        if hosts:
            scopes[name] = (hosts, methods)

    # secrets.env: NAME<TAB>placeholder<TAB>value — only rules with a value
    # become active. A secret's hosts are implicitly allowed and intercepted.
    try:
        with open(paths[4], encoding="utf-8") as f:
            for line in f:
                name, sep, rest = line.rstrip("\n").partition("\t")
                placeholder, sep2, value = rest.partition("\t")
                if not (sep and sep2 and name in scopes and placeholder and value):
                    continue
                hosts, methods = scopes[name]
                policy.secrets.append(Secret(name, hosts, methods, placeholder, value))
                policy.allow.extend(hosts)
    except OSError:
        pass

    _policy_cache.update(key=key, policy=policy)
    return policy


# --- matching ---------------------------------------------------------------

def is_ip(host):
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return False


def parse_pattern(pattern):
    host, sep, port = pattern.rpartition(":")
    if sep and port.isdigit() and ":" not in host:
        return host, int(port)
    return pattern, None


def pattern_matches(pattern, host, port):
    p_host, p_port = parse_pattern(pattern)
    if p_port is not None:
        if port != p_port:
            return False
    elif port not in (443, 80):
        return False
    if p_host.startswith("*."):
        return not is_ip(host) and host.endswith(p_host[1:])
    return host == p_host


def check_rules(policy, host, port):
    """Returns 'deny', an allow-rule string, or None. Deny rules win."""
    if any(pattern_matches(p, host, port) for p in policy.deny):
        return "deny"
    for p in policy.allow:
        if pattern_matches(p, host, port):
            return p
    return None


_PRIVATE_NETS = [ipaddress.ip_network(n) for n in (
    "0.0.0.0/8", "10.0.0.0/8", "100.64.0.0/10", "127.0.0.0/8", "169.254.0.0/16",
    "172.16.0.0/12", "192.168.0.0/16",
    "::/128", "::1/128", "fc00::/7", "fe80::/10",
)]


def is_private_ip(ip):
    addr = ipaddress.ip_address(ip)
    if isinstance(addr, ipaddress.IPv6Address) and addr.ipv4_mapped:
        addr = addr.ipv4_mapped
    return any(addr in net for net in _PRIVATE_NETS)


async def resolve_and_guard(host, policy, reason):
    """Block hostnames that resolve to private ranges (DNS-rebinding guard)
    unless allow-private is set. IP literals were approved as-is by a rule or
    the user, so they pass. mitmproxy resolves again when connecting; the
    tiny TOCTOU window is accepted (the guard is defense-in-depth)."""
    if is_ip(host):
        return True, host, reason
    try:
        infos = await asyncio.get_running_loop().getaddrinfo(host, None)
        address = infos[0][4][0]
    except OSError as exc:
        return False, None, f"dns lookup failed: {getattr(exc, 'strerror', exc)}"
    if is_private_ip(address) and not policy.allow_private:
        return False, None, (
            f"resolves to private address {address} "
            "(set PI_EGRESS_ALLOW_PRIVATE=1 to permit)"
        )
    return True, address, reason


# --- logging ----------------------------------------------------------------

def log_line(verdict, target, reason):
    reason = " ".join(str(reason).split())
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]
    line = f"{stamp}Z {verdict:<6} {target} — {reason}"
    logger.info(line)
    try:
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(line + "\n")
    except OSError:
        pass  # state dir unavailable; the proxy log still has the record


def header_safe(reason):
    return "".join(c if " " <= c <= "~" else " " for c in str(reason))


# --- secret substitution ----------------------------------------------------

def _basic_variants(header_value, needle):
    """True if needle appears in a `Basic <b64>` credential (git-over-HTTPS)."""
    scheme, sep, b64 = header_value.partition(" ")
    if not sep or scheme.lower() != "basic":
        return False
    try:
        return needle in base64.b64decode(b64, validate=True)
    except (binascii.Error, ValueError):
        return False


def _flow_has(flow, needle):
    if needle in flow.request.url.encode():
        return True
    for k, v in flow.request.headers.items():
        raw = v.encode()
        if needle in raw or _basic_variants(v, needle):
            return True
    content = flow.request.get_content(strict=False) or b""
    return needle in content


def _sub_request(flow, old, new):
    url = flow.request.url.encode()
    if old in url:
        flow.request.url = url.replace(old, new).decode()
    for k in list(flow.request.headers.keys(multi=True)):
        v = flow.request.headers[k]
        raw = v.encode()
        if old in raw:
            flow.request.headers[k] = raw.replace(old, new).decode()
        elif _basic_variants(v, old):
            scheme, _, b64 = v.partition(" ")
            decoded = base64.b64decode(b64, validate=True)
            reencoded = base64.b64encode(decoded.replace(old, new)).decode()
            flow.request.headers[k] = f"{scheme} {reencoded}"
    content = flow.request.get_content(strict=False)
    if content and old in content:
        flow.request.content = content.replace(old, new)


def _sub_response(flow, old, new):
    if not flow.response:
        return
    for k in list(flow.response.headers.keys(multi=True)):
        raw = flow.response.headers[k].encode()
        if old in raw:
            flow.response.headers[k] = raw.replace(old, new).decode()
    content = flow.response.get_content(strict=False)
    if content and old in content:
        flow.response.content = content.replace(old, new)


# --- addon ------------------------------------------------------------------

class PiEgress:
    def __init__(self):
        self.session = {}    # "host:port" -> "allow" | "deny"
        self.inflight = {}   # "host:port" -> asyncio.Task
        self._flow_writer = None
        self._gc_task = None  # keep a reference so the task is not GC'd

    def running(self):
        os.makedirs(PENDING_DIR, exist_ok=True)
        os.makedirs(DECISIONS_DIR, exist_ok=True)
        self._gc_task = asyncio.get_running_loop().create_task(self._gc_loop())
        policy = load_policy()
        logger.info(
            "pi-egress addon active (mode=%s, %d allow / %d deny patterns, "
            "%d secrets, record=%s)",
            policy.mode, len(policy.allow), len(policy.deny),
            len(policy.secrets), policy.record,
        )

    # -- filtering --

    async def http_connect(self, flow: http.HTTPFlow):
        host = flow.request.host.lower()
        port = flow.request.port
        allowed, _, reason = await self._decide(host, port)
        log_line("ALLOW" if allowed else "DENY", f"{host}:{port}", reason)
        if not allowed:
            flow.response = http.Response.make(
                403, b"", {"X-Pi-Egress": header_safe(reason)}
            )

    async def request(self, flow: http.HTTPFlow):
        # Plain-HTTP proxy requests never pass through http_connect, so
        # filter them here. Intercepted HTTPS was already gated at CONNECT.
        host = flow.request.host.lower()
        port = flow.request.port
        if flow.request.scheme == "http":
            allowed, _, reason = await self._decide(host, port)
            log_line("ALLOW" if allowed else "DENY", f"{host}:{port}", reason)
            if not allowed:
                flow.response = http.Response.make(
                    403,
                    f"pi-egress: connection to {host}:{port} denied ({reason})\n".encode(),
                    {"Content-Type": "text/plain", "X-Pi-Egress": header_safe(reason)},
                )
                return
        self._inject_secrets(flow, host, port)

    def tls_clienthello(self, data: tls.ClientHelloData):
        # Intercept only hosts covered by intercept= patterns or an active
        # secret; everything else is tunneled without ever being decrypted.
        server = data.context.server.address
        host = (server[0] if server else data.client_hello.sni or "").lower()
        port = server[1] if server else 443
        policy = load_policy()
        if not self._should_intercept(policy, host, port):
            data.ignore_connection = True

    def _should_intercept(self, policy, host, port):
        if policy.intercept_all:
            return True
        patterns = list(policy.intercept)
        for secret in policy.secrets:
            patterns.extend(secret.hosts)
        return any(pattern_matches(p, host, port) for p in patterns)

    async def _decide(self, host, port):
        policy = load_policy()
        match = check_rules(policy, host, port)
        if match == "deny":
            return False, None, "deny rule"
        if match:
            return await resolve_and_guard(host, policy, f"allow rule '{match}'")

        cached = self.session.get(f"{host}:{port}")
        if cached == "deny":
            return False, None, "denied for session"
        if cached == "allow":
            return await resolve_and_guard(host, policy, "allowed for session")

        if policy.mode != "interactive":
            return False, None, "not in allowlist"
        return await self._ask_user(host, port, policy)

    def _ask_user(self, host, port, policy):
        key = f"{host}:{port}"
        if key not in self.inflight:
            task = asyncio.get_running_loop().create_task(
                self._ask_user_inner(host, port, policy)
            )
            task.add_done_callback(lambda _t: self.inflight.pop(key, None))
            self.inflight[key] = task
        return asyncio.shield(self.inflight[key])

    async def _ask_user_inner(self, host, port, policy):
        request_id = pysecrets.token_hex(8)
        pending_file = os.path.join(PENDING_DIR, request_id)
        decision_file = os.path.join(DECISIONS_DIR, request_id)
        with open(pending_file, "w", encoding="utf-8") as f:
            f.write(f"{host}:{port}\n")
        log_line(
            "ASK", f"{host}:{port}",
            f"awaiting decision, {policy.timeout_s}s timeout — answer via 'mise run pi:egress watch'",
        )
        deadline = time.monotonic() + policy.timeout_s
        try:
            while time.monotonic() < deadline:
                await asyncio.sleep(POLL_S)

                # Rules may change while pending (e.g. `pi:egress allow`).
                policy_now = load_policy()
                match = check_rules(policy_now, host, port)
                if match == "deny":
                    return False, None, "deny rule added while pending"
                if match:
                    return await resolve_and_guard(host, policy_now, f"allow rule '{match}'")

                try:
                    with open(decision_file, encoding="utf-8") as f:
                        decision = f.read().strip()
                except OSError:
                    continue
                if decision == "allow-session":
                    self.session[f"{host}:{port}"] = "allow"
                if decision == "deny-session":
                    self.session[f"{host}:{port}"] = "deny"
                if decision.startswith("allow"):
                    return await resolve_and_guard(host, policy_now, "approved by user")
                return False, None, "denied by user"
            return False, None, f"no decision within {policy.timeout_s}s (default deny)"
        finally:
            for path in (pending_file, decision_file):
                try:
                    os.remove(path)
                except OSError:
                    pass

    # -- secrets --

    def _inject_secrets(self, flow, host, port):
        policy = load_policy()
        present = [s for s in policy.secrets if _flow_has(flow, s.placeholder)]
        for secret in present:
            in_scope = any(pattern_matches(p, host, port) for p in secret.hosts)
            if not in_scope or not secret.method_allowed(flow.request.method):
                why = "host not in scope" if not in_scope else f"method {flow.request.method} not allowed"
                log_line(
                    "BLOCK", f"{host}:{port}",
                    f"request carries placeholder for secret '{secret.name}' but {why} — rejected",
                )
                flow.response = http.Response.make(
                    403,
                    f"pi-egress: secret '{secret.name}' is not permitted for "
                    f"{flow.request.method} {host}:{port}\n".encode(),
                    {"Content-Type": "text/plain", "X-Pi-Egress": "secret out of scope"},
                )
                return
        for secret in present:
            _sub_request(flow, secret.placeholder, secret.value)
            flow.metadata.setdefault("pi-egress-secrets", []).append(secret.name)
            log_line(
                "INJECT", f"{host}:{port}",
                f"secret '{secret.name}' injected for {flow.request.method}",
            )

    def _redact(self, flow):
        """Swap real values back to placeholders so neither the client nor
        the recorded flow ever contains a secret."""
        policy = load_policy()
        for secret in policy.secrets:
            _sub_request(flow, secret.value, secret.placeholder)
            _sub_response(flow, secret.value, secret.placeholder)

    # -- recording (post-redaction, so we cannot use --save-stream-file) --

    def response(self, flow: http.HTTPFlow):
        self._redact(flow)
        self._record(flow)

    def error(self, flow: http.HTTPFlow):
        self._redact(flow)
        self._record(flow)

    def _record(self, flow):
        if not load_policy().record:
            return
        try:
            if self._flow_writer is None:
                self._flow_writer = io.FlowWriter(open(FLOWS_FILE, "ab"))
            self._flow_writer.add(flow)
            self._flow_writer.fo.flush()
        except OSError as exc:
            logger.error("cannot record flow: %s", exc)

    # -- housekeeping --

    async def _gc_loop(self):
        """Sweep orphaned pending/decision files (e.g. after a restart)."""
        while True:
            await asyncio.sleep(60)
            now = time.time()
            for directory in (PENDING_DIR, DECISIONS_DIR):
                try:
                    names = os.listdir(directory)
                except OSError:
                    continue
                for name in names:
                    path = os.path.join(directory, name)
                    try:
                        if now - os.stat(path).st_mtime > GC_MAX_AGE_S:
                            os.remove(path)
                    except OSError:
                        pass  # raced with normal cleanup


addons = [PiEgress()]
